'use strict';
require('normalize.css');
require('./index.styl');
require('./components/header');
require('./components/row-wrapper');
require('./components/main-container');
require('./components/summary');
require('./components/featured-scripts');
require('./components/featured-devices');
require('./components/footer');